/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface EIP712Interface extends ethers.utils.Interface {
  functions: {
    "_buildDomainSeparator(bytes32,bytes32,bytes32)": FunctionFragment;
    "_domainSeparatorV4()": FunctionFragment;
    "_hashTypedDataV4(bytes32)": FunctionFragment;
    "check()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_buildDomainSeparator",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "_domainSeparatorV4",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_hashTypedDataV4",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "check", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "_buildDomainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_domainSeparatorV4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_hashTypedDataV4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "check", data: BytesLike): Result;

  events: {};
}

export class EIP712 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: EIP712Interface;

  functions: {
    _buildDomainSeparator(
      typeHash: BytesLike,
      name: BytesLike,
      version: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "_buildDomainSeparator(bytes32,bytes32,bytes32)"(
      typeHash: BytesLike,
      name: BytesLike,
      version: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    _domainSeparatorV4(overrides?: CallOverrides): Promise<[string]>;

    "_domainSeparatorV4()"(overrides?: CallOverrides): Promise<[string]>;

    _hashTypedDataV4(
      structHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "_hashTypedDataV4(bytes32)"(
      structHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    check(
      overrides?: CallOverrides
    ): Promise<[string, string, string, string, BigNumber, string]>;

    "check()"(
      overrides?: CallOverrides
    ): Promise<[string, string, string, string, BigNumber, string]>;
  };

  _buildDomainSeparator(
    typeHash: BytesLike,
    name: BytesLike,
    version: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "_buildDomainSeparator(bytes32,bytes32,bytes32)"(
    typeHash: BytesLike,
    name: BytesLike,
    version: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  _domainSeparatorV4(overrides?: CallOverrides): Promise<string>;

  "_domainSeparatorV4()"(overrides?: CallOverrides): Promise<string>;

  _hashTypedDataV4(
    structHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "_hashTypedDataV4(bytes32)"(
    structHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  check(
    overrides?: CallOverrides
  ): Promise<[string, string, string, string, BigNumber, string]>;

  "check()"(
    overrides?: CallOverrides
  ): Promise<[string, string, string, string, BigNumber, string]>;

  callStatic: {
    _buildDomainSeparator(
      typeHash: BytesLike,
      name: BytesLike,
      version: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "_buildDomainSeparator(bytes32,bytes32,bytes32)"(
      typeHash: BytesLike,
      name: BytesLike,
      version: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    _domainSeparatorV4(overrides?: CallOverrides): Promise<string>;

    "_domainSeparatorV4()"(overrides?: CallOverrides): Promise<string>;

    _hashTypedDataV4(
      structHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "_hashTypedDataV4(bytes32)"(
      structHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    check(
      overrides?: CallOverrides
    ): Promise<[string, string, string, string, BigNumber, string]>;

    "check()"(
      overrides?: CallOverrides
    ): Promise<[string, string, string, string, BigNumber, string]>;
  };

  filters: {};

  estimateGas: {
    _buildDomainSeparator(
      typeHash: BytesLike,
      name: BytesLike,
      version: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_buildDomainSeparator(bytes32,bytes32,bytes32)"(
      typeHash: BytesLike,
      name: BytesLike,
      version: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _domainSeparatorV4(overrides?: CallOverrides): Promise<BigNumber>;

    "_domainSeparatorV4()"(overrides?: CallOverrides): Promise<BigNumber>;

    _hashTypedDataV4(
      structHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_hashTypedDataV4(bytes32)"(
      structHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    check(overrides?: CallOverrides): Promise<BigNumber>;

    "check()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _buildDomainSeparator(
      typeHash: BytesLike,
      name: BytesLike,
      version: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_buildDomainSeparator(bytes32,bytes32,bytes32)"(
      typeHash: BytesLike,
      name: BytesLike,
      version: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _domainSeparatorV4(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_domainSeparatorV4()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _hashTypedDataV4(
      structHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_hashTypedDataV4(bytes32)"(
      structHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    check(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "check()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
